name: Bug Report
description: Report a bug in the github-automated-repos

body:
  - type: dropdown
    id: affected-elements
    attributes:
      label: Which element(s) are the source of the bug?
      options:
        - useGithubAutomatedRepos
        - dataReposGithub
        - ProjectIcon
        - StackIcon
        - IGithubRepos
        - Don't known / other
        
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true


  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in (run `ng version`)
      render: true
      placeholder: |
        Angular CLI: 12.0.5
        Node: 14.17.0
        Package Manager: yarn 1.22.10
        OS: linux x64

        Angular: 12.0.5
        ... animations, cli, common, compiler, compiler-cli, core, forms
        ... platform-browser, platform-browser-dynamic, router

        Package                         Version
        ---------------------------------------------------------
        @angular-devkit/architect       0.1200.5
        @angular-devkit/build-angular   12.0.5
        @angular-devkit/core            12.0.5
        rxjs                            6.6.7
        typescript                      4.2.4

  - type: textarea
    id: other
    attributes:
      label: Anything else?
